In [31]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent
EVAL_DIR =  BASE_DIR / "data" / "evaluation" / "results"

# Load Data
hybrid_rag_path = EVAL_DIR / "hybrid_rag_topk2_results.csv"
hybrid_ref_rag_path = EVAL_DIR /  "hybrid_ref_topn_parent_topk2_results.csv"
graph_rag_path = EVAL_DIR / "graph_topk2_results.csv"
 
# Top k = 2
hybrid_rag_df = pd.read_csv(hybrid_rag_path) 
hybrid_ref_rag_df = pd.read_csv(hybrid_ref_rag_path) 
graph_rag_df = pd.read_csv(graph_rag_path)

In [21]:
hybrid_rag_df.head(1)

,id,system,question,rag_answer,gt_reference_answer,gt_answer,prompt_tokens,completion_tokens,total_tokens,retrieve_time,llm_time,total_elapsed,hit_rate,multi_hit_rate,recall,mrr,rouge1_recall,rougeL_recall,bertscore_recall
0,0,hybrid_rag,การเเสดงเจตนาตัดมิให้รับมรดกจะถอนได้หรือไม่,การแสดงเจตนาตัดมิให้รับมรดกสามารถถอนเสียได้ ตา...,ได้,ได้ ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1609 กา...,1053,175,1228,0.070329,3.538575,3.608903,1,1,1.0,1.0,0.0,0.0,0.967864

In [33]:
from functools import reduce

# Scnario 1
# All Correct

# Multi-HitRate = 1
hybrid_rag_df_filter = hybrid_rag_df[hybrid_rag_df["multi_hit_rate"] == 1]
hybrid_ref_rag_df_filter = hybrid_ref_rag_df[hybrid_ref_rag_df["multi_hit_rate"] == 1]
graph_rag_filter = graph_rag_df[graph_rag_df["multi_hit_rate"] == 1]

# Intersection with id
dfs = [hybrid_rag_df_filter, hybrid_ref_rag_df_filter, graph_rag_filter]

# Intersect based on a common column named 'ID'
df_intersection = reduce(lambda left, right: pd.merge(left, right, on='id', how='inner'), dfs)

In [34]:
df_intersection.head(5)

,id,system_x,question_x,rag_answer_x,gt_reference_answer_x,gt_answer_x,prompt_tokens_x,completion_tokens_x,total_tokens_x,retrieve_time_x,...,retrieve_time,llm_time,total_elapsed,hit_rate,multi_hit_rate,recall,mrr,rouge1_recall,rougeL_recall,bertscore_recall
0,0,hybrid_rag,การเเสดงเจตนาตัดมิให้รับมรดกจะถอนได้หรือไม่,การแสดงเจตนาตัดมิให้รับมรดกสามารถถอนเสียได้ ตา...,ได้,ได้ ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1609 กา...,1053,175,1228,0.070329,...,6.251553,3.490913,9.742465,1,1,1.0,1.0,0.0,0.0,0.973682
1,5,hybrid_rag,หากมีเหตุสุดวิสัยมาขัดขวางไม่ให้เจ้าหนี้ฟ้องคด...,ตามประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 193/19 หาก...,ให้ถือว่าอายุความยังไม่ครบกำหนดจนกว่าจะพ้น 30 ...,ให้ถือว่าอายุความยังไม่ครบกำหนดจนกว่าจะพ้น 30 ...,1113,117,1230,0.198600,...,0.178010,2.361912,2.539923,1,1,1.0,1.0,0.0,0.0,0.922633
2,18,hybrid_rag,หากปรากฏว่าบุคคลที่ศาลตั้งให้เป็นผู้ปกครองเป็น...,ตามประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1588 ศาลต้...,ให้ศาลสั่งเพิกถอนคำสั่งตั้งผู้ปกครองนั้นเสียแล...,ให้ศาลสั่งเพิกถอนคำสั่งตั้งผู้ปกครองนั้นเสียแล...,1263,76,1339,0.159650,...,0.144390,1.506727,1.651117,1,1,1.0,1.0,0.0,0.0,0.876218
3,23,hybrid_rag,ใครเป็นผู้มีอำนาจถอดถอนผู้ปกครอง หากผู้นั้นมีค...,ผู้มีอำนาจถอดถอนผู้ปกครองหากมีความพฤติกรรมไม่เ...,ศาลเป็นผู้มีอำนาจสั่ง,ศาลเป็นผู้มีอำนาจสั่ง,1142,115,1257,0.164391,...,0.142462,3.891220,4.033682,1,1,1.0,1.0,0.0,0.0,0.808790
4,27,hybrid_rag,ถ้าสามีหรือภริยาได้ยินยอมหรือรู้เห็นเป็นใจในกา...,ไม่ได้ ตามมาตรา 1517 แห่งประมวลกฎหมายแพ่งและพา...,ฝ่ายที่ยินยอมหรือรู้เห็นเป็นใจนั้นจะยกเป็นเหตุ...,ฝ่ายที่ยินยอมหรือรู้เห็นเป็นใจนั้นจะยกเป็นเหตุ...,2369,101,2470,0.163947,...,0.139233,2.078904,2.218137,1,1,1.0,1.0,0.0,0.0,0.950142

In [35]:
# Scnario 2
# Hybrid RAG Fail , Rest Correct

hybrid_rag_df_filter = hybrid_rag_df[hybrid_rag_df["multi_hit_rate"] == 0]
hybrid_ref_rag_df_filter = hybrid_ref_rag_df[hybrid_ref_rag_df["multi_hit_rate"] == 1]
graph_rag_filter = graph_rag_df[graph_rag_df["multi_hit_rate"] == 1]

# Intersection with id
dfs = [hybrid_rag_df_filter, hybrid_ref_rag_df_filter, graph_rag_filter]

# Intersect based on a common column named 'ID'
df_intersection = reduce(lambda left, right: pd.merge(left, right, on='id', how='inner'), dfs)

In [36]:
df_intersection.head(5)

,id,system_x,question_x,rag_answer_x,gt_reference_answer_x,gt_answer_x,prompt_tokens_x,completion_tokens_x,total_tokens_x,retrieve_time_x,...,retrieve_time,llm_time,total_elapsed,hit_rate,multi_hit_rate,recall,mrr,rouge1_recall,rougeL_recall,bertscore_recall
0,1,hybrid_rag,การแปรสภาพห้างหุ้นส่วนจำกัดเป็นบริษัทจำกัด ต้อ...,การแปรสภาพห้างหุ้นส่วนจำกัดเป็นบริษัทจำกัด ต้อ...,ภายใน 14 วันนับแต่วันที่ผู้เป็นหุ้นส่วนได้ให้ค...,หุ้นส่วนผู้จัดการต้องส่งมอบกิจการ ทรัพย์สิน บั...,1356,102,1458,0.095451,...,0.069775,2.669925,2.739701,1,1,1.0,0.333333,0.666667,0.666667,0.888680
1,3,hybrid_rag,พ่อแม่โดยกำเนิดกลับมามีอำนาจปกครองเมื่อไร,พ่อแม่โดยกำเนิดไม่สามารถกลับมามีอำนาจปกครองบุต...,นับแต่เวลาที่ผู้รับบุตรบุญธรรมตาย หรือนับแต่เว...,นับแต่เวลาที่ผู้รับบุตรบุญธรรมตาย หรือนับแต่เว...,1074,123,1197,0.145646,...,0.078019,2.960365,3.038383,1,1,1.0,0.500000,0.000000,0.000000,0.945682
2,4,hybrid_rag,ระยะเวลาในการฟ้องคดีมรดกมีหลักเกณฑ์อย่างไร,ตามประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1754 กำหนด...,ห้ามมิให้ฟ้องคดีมรดกเมื่อพ้นกำหนดหนึ่งปี นับแต...,ห้ามมิให้ฟ้องคดีมรดกเมื่อพ้นกำหนดหนึ่งปี นับแต...,1392,264,1656,0.148808,...,0.145899,2.435178,2.581077,1,1,1.0,1.000000,0.000000,0.000000,0.918890
3,6,hybrid_rag,ถูกตั้งให้เป็นตัวแทนแต่ผู้ตั้งตัวแทนไม่อยู่และ...,ได้ ตามมาตรา 49 แห่งประมวลกฎหมายแพ่งและพาณิชย์...,ศาลจะสั่งให้ทำการอย่างใดอย่างหนึ่งไปพลางเพื่อจ...,ในกรณีที่ผู้ไม่อยู่ได้ตั้งตัวแทนผู้รับมอบอำนาจ...,1088,155,1243,0.161112,...,0.158938,4.547053,4.705991,1,1,1.0,1.000000,0.000000,0.000000,0.956156
4,9,hybrid_rag,ผู้ค้ำประกันตกลงรับผิดในฐานะลูกหนี้ร่วมได้หรือไม่,ผู้ค้ำประกันไม่สามารถตกลงรับผิดในฐานะลูกหนี้ร่...,ผู้ค้ำประกันไม่สามารถรับผิดอย่างลูกหนี้ร่วมได้...,ผู้ค้ำประกันไม่สามารถรับผิดอย่างลูกหนี้ร่วมได้...,1039,93,1132,0.171516,...,0.145909,1.868579,2.014489,1,1,1.0,0.500000,0.000000,0.000000,0.911876

In [37]:
# Scnario 3
# All Fail

hybrid_rag_df_filter = hybrid_rag_df[hybrid_rag_df["multi_hit_rate"] == 0]
hybrid_ref_rag_df_filter = hybrid_ref_rag_df[hybrid_ref_rag_df["multi_hit_rate"] == 0]
graph_rag_filter = graph_rag_df[graph_rag_df["multi_hit_rate"] == 0]

# Intersection with id
dfs = [hybrid_rag_df_filter, hybrid_ref_rag_df_filter, graph_rag_filter]

# Intersect based on a common column named 'ID'
df_intersection = reduce(lambda left, right: pd.merge(left, right, on='id', how='inner'), dfs)

In [38]:
df_intersection.head(5)

,id,system_x,question_x,rag_answer_x,gt_reference_answer_x,gt_answer_x,prompt_tokens_x,completion_tokens_x,total_tokens_x,retrieve_time_x,...,retrieve_time,llm_time,total_elapsed,hit_rate,multi_hit_rate,recall,mrr,rouge1_recall,rougeL_recall,bertscore_recall
0,2,hybrid_rag,ซื้อหวยใต้ดิน แล้วเขาไม่จ่าย ฟ้องได้ไหม,ไม่สามารถฟ้องร้องเพื่อขอค่าเสียหายจากการซื้อหว...,ไม่ได้ เพราะมีแค่เพียง สลากกินแบ่งของรัฐบาลเท่...,ไม่ได้ เพราะมีแค่เพียง สลากกินแบ่งของรัฐบาลเท่...,1048,114,1162,0.241677,...,0.132953,2.633224,2.766177,0,0,0.000000,0.0,0.000000,0.000000,0.836057
1,7,hybrid_rag,การที่นายทะเบียนขีดชื่อบริษัทจำกัด ออกจากทะเบี...,เมื่อนายทะเบียนขีดชื่อบริษัทจำกัดออกจากทะเบียน...,บริษัทจำกัดนั้น สิ้นสภาพนิติบุคลตั้งแต่เมื่อนา...,บริษัทจำกัดนั้น สิ้นสภาพนิติบุคลตั้งแต่เมื่อนา...,1470,172,1642,0.147792,...,0.143299,4.725745,4.869044,1,0,0.333333,0.0,0.000000,0.000000,0.851893
2,8,hybrid_rag,ฟ้องหย่ากรณีโดนสามีทำร้ายร่างกายต้องใช้สิทธิภา...,ตามประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1516 (ข) บ...,ต้องใช้สิทธิภายในกำหนด 1 ปีนับแต่วันผู้คนอ้างร...,กรณีนี้เป็นการใช้สิทธิฟ้องตามเหตุในมาตรา 1516(...,2207,202,2409,0.138810,...,0.142223,4.149060,4.291283,1,0,0.333333,0.0,0.000000,0.000000,0.826530
3,17,hybrid_rag,หากคู่สมรสของเจ้ามรดกยังมีชีวิตอยู่ และมีทายาท...,ตามประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1635 ลำดับ...,ต้องแบ่งมรดกให้แก่คู่สมรสของเจ้ามรดกนั้นก่อนตา...,ต้องแบ่งมรดกให้แก่คู่สมรสของเจ้ามรดกนั้นก่อนตา...,1544,440,1984,0.169501,...,0.151922,3.364667,3.516590,1,0,0.500000,0.0,0.000000,0.000000,0.891865
4,28,hybrid_rag,รายการใดบ้างที่ต้องระบุตอนขอจดทะเบียนบริษัท,ต้องระบุรายการดังต่อไปนี้เมื่อขอจดทะเบียนบริษั...,รายการที่ต้องระบุมี 8 รายการ ดังนี้ 1 จำนวนหุ้...,รายการที่ต้องระบุมี 8 รายการ ดังนี้ 1 จำนวนหุ้...,1494,328,1822,0.166183,...,0.140712,6.398711,6.539423,0,0,0.000000,0.0,0.666667,0.666667,0.841557