In [1]:
from neo4j import GraphDatabase
from neo4j_graphrag.experimental.pipeline.kg_builder import SimpleKGPipeline
from neo4j_graphrag.llm import OpenAILLM, OllamaLLM
from neo4j_graphrag.embeddings import OpenAIEmbeddings
from neo4j_graphrag.generation.prompts import ERExtractionTemplate
from dotenv import load_dotenv
import pandas as pd
from langchain_core.documents import Document
from langchain_community.llms import Ollama
from neo4j_graphrag.retrievers import VectorRetriever, VectorCypherRetriever, Text2CypherRetriever
from neo4j_graphrag.schema import get_schema
from neo4j_graphrag.generation import GraphRAG


import os, time, asyncio, glob, csv

d:\GitHub\muict_thai_legal_RAG_GraphRAG\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Initialize Graph Database

In [2]:
load_dotenv(dotenv_path="../.env")

URI = os.getenv("NEO4J_URI")
USERNAME = os.getenv("NEO4J_USERNAME")
PASSWORD = os.getenv("NEO4J_PASSWORD")
DATABASE_NAME = os.getenv("NEO4J_DATABASE")

driver = GraphDatabase.driver(URI, auth=(USERNAME, PASSWORD))

### 1.1 Call BGE-M3 Embedding model

In [3]:
import torch
from FlagEmbedding import BGEM3FlagModel

# เช็คว่ามี GPU (CUDA) หรือไม่
# ถ้ามีให้ใช้ 'cuda' ถ้าไม่มีให้ใช้ 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'cpu'
use_fp16 = True if device == 'cuda' else False  # fp16 ส่วนใหญ่รองรับเฉพาะบน GPU

print(f"กำลังรันโมเดลบน: {device.upper()}")

# 2. Initialize Model
embedder = BGEM3FlagModel(
    'VISAI-AI/nitibench-ccl-human-finetuned-bge-m3', 
    use_fp16=use_fp16, 
    device=device 
)

กำลังรันโมเดลบน: CUDA

Fetching 23 files: 100%|██████████| 23/23 [00:00<?, ?it/s]

### 1.2 Wrap embedding model
เนื่องจาก Embedding model ที่จะใช้ใน Neo4J (เรียกจาก library Neo4J โดยตรง ไม่ใช่ langchain) ไม่สามารถเรียกใช้ Embedding model BGE-M3 ได้โดยตรง ตัว Library รองรับแค่พวก Commercial Models e.g. openai จึงต้องมีการ Wrap เพื่อให้ใช้งานได้

In [4]:
from neo4j_graphrag.embeddings import Embedder

class Neo4jCompatibleEmbedder(Embedder):
    def __init__(self, original_embedder):
        self.original_embedder = original_embedder

    def embed_query(self, text: str) -> list[float]:
        # 1. เรียกโมเดล M3 (สมมติว่าใช้ .encode)
        result = self.original_embedder.encode(text)
        
        # 2. ตรวจสอบว่าผลลัพธ์เป็น dict หรือไม่ (BGE-M3 มักคืนค่าแบบนี้ถ้าไม่ได้ตั้ง return_dense_only=True)
        if isinstance(result, dict):
            # ดึงเฉพาะ Dense Vector ออกมา
            embedding = result.get('dense_vecs')
        else:
            embedding = result

        # 3. แปลงจาก numpy array เป็น list เพื่อให้ Pydantic/Neo4j ยอมรับ
        if hasattr(embedding, "tolist"):
            return embedding.tolist()
        
        # กรณีเป็น list อยู่แล้วแต่สมาชิกข้างในอาจเป็น numpy types ให้วนลูปแปลง (ถ้าจำเป็น)
        return [float(x) for x in embedding]

    def embed_nodes(self, nodes):
        for node in nodes:
            # node.text คือเนื้อหาที่ถูก Chunk แล้ว
            node.embedding = self.embed_query(node.text)

# การใช้งาน
# ระวังอย่ารันบรรทัดนี้ซ้ำ (เพราะจะกลายเป็น wrap ซ้อน wrap)
neo4j_embedder = Neo4jCompatibleEmbedder(embedder)

In [5]:
df = pd.read_parquet('../data/processed/ref_vectors_sparse_nitibench-ccl-bge-m3.parquet')
df.head()

,id,law_name,section_num,text,dense_vector,sparse_vector,reference_laws
0,0,พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546,132,พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มา...,"[-0.03570556640625, 0.004070281982421001, -0.0...","{""221767"": 0.060760498046875, ""70390"": 0.15673...",[{'law_name': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน...
1,1,ประมวลกฎหมายแพ่งและพาณิชย์,1598/5,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5\nถ้าผู...,"[0.0345458984375, 0.049072265625, -0.020095825...","{""130047"": 0.0031299591064453125, ""57467"": 0.0...",[]
2,2,ประมวลกฎหมายแพ่งและพาณิชย์,876,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 876\nถ้าผู้รั...,"[-0.039886474609375, 0.05941772460937501, 0.00...","{""167120"": 0.015411376953125, ""382"": 0.0497741...",[]
3,3,ประมวลกฎหมายแพ่งและพาณิชย์,1030,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1030\nถ้าผู้เ...,"[-0.029144287109375003, 0.024978637695312, -0....","{""130047"": 0.11090087890625, ""57467"": 0.025955...",[]
4,4,ประมวลกฎหมายแพ่งและพาณิชย์,849,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 849\nการรับเง...,"[0.011123657226562, 0.0675048828125, -0.041503...","{""130047"": 0.00732421875, ""57467"": 0.020690917...",[]

In [ ]:
len(df)

3833

In [ ]:
df['reference_laws'] = df['reference_laws'].astype(str)

In [8]:
df['law_name'].value_counts()

law_name
ประมวลกฎหมายแพ่งและพาณิชย์                                                                                          1661
พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535                                                                   398
ประมวลรัษฎากร                                                                                                        351
พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. 2535                                                                              199
พระราชบัญญัติธุรกิจสถาบันการเงิน พ.ศ. 2551                                                                           165
พระราชบัญญัติการประกอบกิจการพลังงาน พ.ศ. 2550                                                                        153
พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546                                                                          131
พระราชบัญญัติภาษีเงินได้ปิโตรเลียม พ.ศ. 2514                                                                          99
พระราชกำหนดการประกอบธุรกิจสินทรัพย์ดิจิทัล พ.ศ. 2561                                                                  87
พระราชบัญญัติทรัสต์เพื่อธุรกรรมในตลาดทุน พ.ศ. 2550                                                                    86
พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558                                                                            81
พระราชบัญญัติวิชาชีพบัญชี พ.ศ. 2547                                                                                   68
พระราชบัญญัติการส่งเสริมการอนุรักษ์พลังงาน พ.ศ. 2535                                                                  58
พระราชบัญญัติกำหนดความผิดเกี่ยวกับห้างหุ้นส่วนจดทะเบียน ห้างหุ้นส่วนจำกัด บริษัทจำกัด สมาคม และมูลนิธิ พ.ศ. 2499      48
พระราชบัญญัติสมาคมการค้า พ.ศ. 2509                                                                                    44
พระราชบัญญัติการบัญชี พ.ศ. 2543                                                                                       41
พระราชบัญญัติกองทุนสำรองเลี้ยงชีพ พ.ศ. 2530                                                                           41
พระราชบัญญัติการประกอบธุรกิจของคนต่างด้าว พ.ศ. 2542                                                                   39
พระราชกำหนดนิติบุคคลเฉพาะกิจเพื่อการแปลงสินทรัพย์เป็นหลักทรัพย์ พ.ศ. 2540                                             36
พระราชบัญญัติหอการค้า พ.ศ. 2509                                                                                       34
พระราชบัญญัติทะเบียนพาณิชย์ พ.ศ. 2499                                                                                 12
พระราชบัญญัติทุนรัฐวิสาหกิจ พ.ศ. 2542                                                                                  1
Name: count, dtype: int64

In [ ]:
df[df['law_name'] == 'ประมวลกฎหมายแพ่งและพาณิชย์'].head()

,id,law_name,section_num,text,dense_vector,sparse_vector,reference_laws
1,1,ประมวลกฎหมายแพ่งและพาณิชย์,1598/5,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/5\nถ้าผู...,"[0.0345458984375, 0.049072265625, -0.020095825...","{""130047"": 0.0031299591064453125, ""57467"": 0.0...",[]
2,2,ประมวลกฎหมายแพ่งและพาณิชย์,876,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 876\nถ้าผู้รั...,"[-0.039886474609375, 0.05941772460937501, 0.00...","{""167120"": 0.015411376953125, ""382"": 0.0497741...",[]
3,3,ประมวลกฎหมายแพ่งและพาณิชย์,1030,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1030\nถ้าผู้เ...,"[-0.029144287109375003, 0.024978637695312, -0....","{""130047"": 0.11090087890625, ""57467"": 0.025955...",[]
4,4,ประมวลกฎหมายแพ่งและพาณิชย์,849,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 849\nการรับเง...,"[0.011123657226562, 0.0675048828125, -0.041503...","{""130047"": 0.00732421875, ""57467"": 0.020690917...",[]
6,6,ประมวลกฎหมายแพ่งและพาณิชย์,565,ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 565\nการเช่าถ...,"[-0.03216552734375, 0.05874633789062501, -0.03...","{""57467"": 0.0092620849609375, ""167120"": 0.0239...",[]

## 2. Chunking to documents

In [48]:
START = 100
END = 150

def batch_document_append(df,start=0, end=len(df)):
    documents = []
    for index, row in df.iloc[start:end,:].iterrows():
        # สร้างเนื้อหาที่มีบริบทชัดเจนในตัวเอง
        content = f"กฎหมาย: {row['law_name']}\nเนื้อหา: {row['section_content']}"
        
        # เก็บ Metadata เพื่อใช้ในภายหลัง
        metadata = {
            "law_name": row['law_name'],
        }
        documents.append(Document(page_content=content, metadata=metadata))
    return documents

documents = batch_document_append(df,start=START, end=END)
documents

[Document(metadata={'law_name': 'พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535'}, page_content='กฎหมาย: พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535\nเนื้อหา: พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535 มาตรา 189 บุคคลใดประสงค์จะนำหลักทรัพย์ที่ตนออกไปซื้อขายในตลาดหลักทรัพย์ จะต้องนำหลักทรัพย์นั้นไปจดทะเบียนกับตลาดหลักทรัพย์\nเมื่อตลาดหลักทรัพย์ได้รับคำขอจดทะเบียนแล้ว ให้พิจารณาและเสนอความเห็นต่อคณะกรรมการตลาดหลักทรัพย์เพื่อสั่งรับหรือไม่รับเป็นหลักทรัพย์จดทะเบียน'),
 Document(metadata={'law_name': 'พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. 2535'}, page_content='กฎหมาย: พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. 2535\nเนื้อหา: พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. 2535 มาตรา 205 บริษัทใดไม่ปฏิบัติตามมาตรา 109 มีความผิดทางพินัยต้องชำระค่าปรับเป็นพินัยไม่เกินสองแสนบาท และชำระค่าปรับเป็นพินัยรายวันอีกวันละสองพันบาท*จนกว่าจะปฏิบัติถูกต้อง'),
 Document(metadata={'law_name': 'พระราชบัญญัติทรัสต์เพื่อธุรกรรมในตลาดทุน พ.ศ. 2550'}, page_content='กฎหมาย: พระราชบัญญัติทรัสต์เพื่อธุรกรรมในตลาดทุน พ.ศ. 2550\nเนื้อหา: พระราชบัญญัติทรัสต์เพื่อธุรกรรมในตลาดทุน พ.ศ. 2550 มาตรา 46 ในกรณีที่ผู้รับประโยชน์แจ้งให้ทรัสตีรายใหม่ปฏิบัติหน้าที่ตามมาตรา 40 ภายในระยะเวลาอันสมควรแล้ว แต่ทรัสตีรายใหม่ยังมิได้ปฏิบัติหน้าที่ภายในระยะเวลาดังกล่าว ผู้รับประโยชน์มีสิทธิเรียกร้องค่าเสียหายจากทรัสตีรายที่ต้องรับผิด หรือใช้สิทธิติดตามเอาทรัพย์สินคืนจากบุคคลภายนอก แล้วแต่กรณี เพื่อประโยชน์ของกองทรัสต์ได้ และให้นำความในมาตรา 44 วรรคสาม มาใช้บังคับโดยอนุโลม'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1243\nบริษัทใหม่นี้ย่อมได้ไปทั้งสิทธิและความรับผิดบรรดามีอยู่แก่บริษัทเดิมอันได้มาควบเข้ากันนั้นทั้งสิ้น'),
 Document(metadata={'law_name': 'พระราชบัญญัติการประกอบธุรกิจของคนต่างด้าว พ.ศ. 2542'}, page_content='กฎหมาย: พระราชบัญญัติการประกอบธุรกิจของคนต่างด้าว พ.ศ. 2542\nเนื้อหา: พระราชบัญญัติการประกอบธุรกิจของคนต่างด้าว พ.ศ. 2542 มาตรา 37 คนต่างด้าวผู้ใดประกอบธุรกิจโดยฝ่าฝืนมาตรา 6 มาตรา 7 หรือมาตรา 8 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับตั้งแต่หนึ่งแสนบาทถึงหนึ่งล้านบาท หรือทั้งจำทั้งปรับ และให้ศาลสั่งเลิกการประกอบธุรกิจ หรือเลิกกิจการ หรือสั่งเลิกการเป็นผู้ถือหุ้น หรือเป็นหุ้นส่วน แล้วแต่กรณี หากฝ่าฝืนไม่ปฏิบัติตามคำสั่งศาลต้องระวางโทษปรับวันละหนึ่งหมื่นบาทถึงห้าหมื่นบาทตลอดเวลาที่ยังฝ่าฝืนอยู่'),
 Document(metadata={'law_name': 'พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558'}, page_content='กฎหมาย: พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558\nเนื้อหา: พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558 มาตรา 38 เมื่อมีเหตุบังคับหลักประกันตามสัญญาหลักประกันทางธุรกิจ และผู้รับหลักประกันได้มีหนังสือแจ้งเหตุบังคับหลักประกันแล้ว ห้ามมิให้ผู้ให้หลักประกันจำหน่ายจ่ายโอนทรัพย์สินที่เป็นหลักประกันหรือกระทำการใด ๆ อันทำให้ทรัพย์สินที่เป็นหลักประกันบุบสลายหรือเสื่อมค่าลง และให้ผู้รับหลักประกันมีสิทธิเข้าครอบครองทรัพย์สินที่เป็นหลักประกัน\nการใช้สิทธิเข้าครอบครองทรัพย์สินที่เป็นหลักประกันตามวรรคหนึ่ง ต้องไม่ขัดต่อความสงบเรียบร้อยหรือศีลธรรมอันดีของประชาชน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1507\nถ้าคู่สมรสได้ทำการสมรสโดยถูกข่มขู่อันถึงขนาดซึ่งถ้ามิได้มีการข่มขู่นั้นจะไม่ทำการสมรส การสมรสนั้นเป็นโมฆียะ\nสิทธิขอเพิกถอนการสมรสเพราะถูกข่มขู่เป็นอันระงับ เมื่อเวลาได้ผ่านพ้นไปแล้วหนึ่งปีนับแต่วันที่พ้นจากการข่มขู่'),
 Document(metadata={'law_name': 'พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535'}, page_content='กฎหมาย: พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535\nเนื้อหา: พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535 มาตรา 48 ในกรณีที่ผู้แทนผู้ถือหุ้นกู้กระทำความผิดเกี่ยวกับทรัพย์ตามบทบัญญัติในหมวด 1 หมวด 3 หมวด 4 หมวด 5 หรือหมวด 7 ของลักษณะ 12 แห่งประมวลกฎหมายอาญา ให้สำนักงานเป็นผู้เสียหายตามประมวลกฎหมายวิธีพิจารณาความอาญาด้วย\nในกรณีตามวรรคหนึ่ง เมื่อพนักงานอัยการยื่นฟ้องคดีอาญา ให้พนักงานอัยการมีอำนาจเรียกทรัพย์สินหรือราคาหรือค่าสินไหมทดแทนเพื่อความเสียหายแทนผู้ได้รับความเสียหายด้วย ในการนี้ ให้นำบทบัญญัติว่าด้วยการฟ้องคดีแพ่งที่เกี่ยวเนื่องกับคดีอาญาตามประมวลกฎหมายวิธีพิจารณาความอาญามาใช้บังคับโดยอนุโลม'),
 Document(metadata={'law_name': 'ประมวลรัษฎากร'}, page_content='กฎหมาย: ประมวลรัษฎากร\nเนื้อหา: ประมวลรัษฎากร มาตรา 27 จัตวา เพื่อประโยชน์ในการคืนภาษีอากรตามบทบัญญัติแห่งประมวลรัษฎากร เจ้าพนักงานประเมินอาจส่งหนังสือแจ้งความแก่ผู้มีสิทธิขอคืน หรือบุคคลอื่นที่เกี่ยวข้องมาให้ถ้อยคำ หรือส่งเอกสาร หรือหลักฐานอันควรแก่เรื่องเพื่อประกอบการพิจารณาได้ตามที่เห็นสมควร'),
 Document(metadata={'law_name': 'ประมวลรัษฎากร'}, page_content='กฎหมาย: ประมวลรัษฎากร\nเนื้อหา: ประมวลรัษฎากร มาตรา 29 ในการอุทธรณ์การประเมินภาษีอากรที่อำเภอมีหน้าที่ประเมิน ให้อุทธรณ์ได้ตามเกณฑ์และวิธีการ ดังต่อไปนี้\n(1) ให้อุทธรณ์การประเมินของอำเภอต่อเจ้าพนักงานประเมินภายในกำหนด 15 วัน นับแต่วันได้รับแจ้งการประเมิน\n(2) เว้นแต่ในกรณีห้ามอุทธรณ์ตามความในมาตรา 21 หรือมาตรา 25 ให้อุทธรณ์การประเมินของเจ้าพนักงานประเมินต่อผู้ว่าราชการจังหวัดภายในกำหนดสิบห้าวัน นับแต่วันได้รับแจ้งคำวินิจฉัยอุทธรณ์ หรือรับแจ้งการประเมินตามความในมาตรา 18 ทวิ มาตรา 20 หรือ มาตรา 24\n(3) เว้นแต่ในกรณีห้ามอุทธรณ์ตามมาตรา 33 ให้อุทธรณ์คำวินิจฉัยอุทธรณ์ของข้าหลวงประจำจังหวัดต่อศาลภายในกำหนด 15 วัน นับแต่วันที่ได้รับแจ้งคำวินิจฉัยอุทธรณ์'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/4\nเงินได้ของผู้อยู่ในปกครองนั้น ผู้ปกครองย่อมใช้ได้ตามสมควรเพื่อการอุปการะเลี้ยงดูและการศึกษาของผู้อยู่ในปกครอง ถ้ามีเหลือให้ใช้เพื่อแสวงหาผลประโยชน์ เฉพาะในเรื่องต่อไปนี้\n(1) ซื้อพันธบัตรรัฐบาลไทยหรือพันธบัตรที่รัฐบาลไทยค้ำประกัน\n(2) รับขายฝากหรือรับจำนองอสังหาริมทรัพย์ในลำดับแรก แต่จำนวนเงินที่รับขายฝากหรือรับจำนองต้องไม่เกินกึ่งราคาตลาดของอสังหาริมทรัพย์นั้น\n(3) ฝากประจำในธนาคารที่ได้ตั้งขึ้นโดยกฎหมายหรือที่ได้รับอนุญาตให้ประกอบกิจการในราชอาณาจักร\n(4) ลงทุนอย่างอื่นซึ่งศาลอนุญาตเป็นพิเศษ'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1131\nในระหว่างสิบสี่วันก่อนการประชุมใหญ่สามัญ บริษัทจะปิดสมุดทะเบียนพักการโอนหุ้นเสียก็ได้'),
 Document(metadata={'law_name': 'ประมวลรัษฎากร'}, page_content='กฎหมาย: ประมวลรัษฎากร\nเนื้อหา: ประมวลรัษฎากร มาตรา 82/17 บทบัญญัติมาตรา 82/16 มิได้เป็นการห้ามผู้ประกอบการที่จะใช้สิทธิเสียภาษีมูลค่าเพิ่มตามที่กำหนดในมาตรา 82/3 แต่เมื่อใช้สิทธิดังกล่าวแล้วจะขอให้นำมาตรา 82/16 มาใช้บังคับอีกไม่ได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1498\nการสมรสที่เป็นโมฆะ ไม่ก่อให้เกิดความสัมพันธ์ทางทรัพย์สินระหว่างสามีภริยา\nในกรณีที่การสมรสเป็นโมฆะ ทรัพย์สินที่ฝ่ายใดมีหรือได้มาไม่ว่าก่อนหรือหลังการสมรสรวมทั้งดอกผลคงเป็นของฝ่ายนั้น ส่วนบรรดาทรัพย์สินที่ทำมาหาได้ร่วมกันให้แบ่งคนละครึ่ง เว้นแต่ศาลจะเห็นสมควรสั่งเป็นประการอื่น เมื่อได้พิเคราะห์ถึงภาระในครอบครัว ภาระในการหาเลี้ยงชีพ และฐานะของคู่กรณีทั้งสองฝ่าย ตลอดจนพฤติการณ์อื่นทั้งปวงแล้ว'),
 Document(metadata={'law_name': 'พระราชบัญญัติกองทุนสำรองเลี้ยงชีพ พ.ศ. 2530'}, page_content='กฎหมาย: พระราชบัญญัติกองทุนสำรองเลี้ยงชีพ พ.ศ. 2530\nเนื้อหา: พระราชบัญญัติกองทุนสำรองเลี้ยงชีพ พ.ศ. 2530 มาตรา 23/3 เมื่อลูกจ้างรายใดสิ้นสมาชิกภาพเพราะออกจากงานไม่ว่าด้วยเหตุใด ลูกจ้างรายนั้นมีสิทธิคงเงินทั้งหมดที่มีสิทธิจะได้รับไว้ในกองทุน และคงการเป็นสมาชิกต่อไป โดยลูกจ้างและนายจ้างไม่ต้องจ่ายเงินสะสมและเงินสมทบเข้ากองทุน ทั้งนี้ ตามระยะเวลาที่กำหนดในข้อบังคับของกองทุนโดยระยะเวลาที่กำหนดไว้ในข้อบังคับดังกล่าวต้องไม่น้อยกว่าเก้าสิบวันนับแต่วันที่ออกจากงาน'),
 Document(metadata={'law_name': 'พระราชบัญญัติหอการค้า พ.ศ. 2509'}, page_content='กฎหมาย: พระราชบัญญัติหอการค้า พ.ศ. 2509\nเนื้อหา: พระราชบัญญัติหอการค้า พ.ศ. 2509 มาตรา 17 ห้ามมิให้บุคคลใดใช้ชื่อที่มีอักษรไทยประกอบว่า “หอการค้า” หรือ “สภาหอการค้าแห่งประเทศไทย” หรืออักษรต่างประเทศซึ่งแปลหรืออ่านว่า “หอการค้า” หรือ “สภาหอการค้าแห่งประเทศไทย” ในดวงตรา ป้ายชื่อ จดหมาย ใบแจ้งความ หรือเอกสารอย่างอื่นอันเกี่ยวกับธุรกิจ โดยมิได้เป็นหอการค้า เว้นแต่เป็นการใช้ในการขออนุญาตจัดตั้งหอการค้า'),
 Document(metadata={'law_name': 'พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. 2535'}, page_content='กฎหมาย: พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. 2535\nเนื้อหา: พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. 2535 มาตรา 147 บริษัทต้องมีหนังสือแจ้งมติการที่จะควบกันกับบริษัทอื่นไปยังเจ้าหนี้ของบริษัท และให้นำมาตรา 141 มาใช้บังคับโดยอนุโลม'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 912\nอันตั๋วแลกเงินนั้นจะออกสั่งให้ใช้เงินตามคำสั่งของผู้สั่งจ่ายก็ได้\nอนึ่ง จะสั่งจ่ายเอาจากตัวผู้สั่งจ่ายเอง หรือสั่งจ่ายเพื่อบุคคลภายนอกก็ได้'),
 Document(metadata={'law_name': 'พระราชกำหนดการประกอบธุรกิจสินทรัพย์ดิจิทัล พ.ศ. 2561'}, page_content='กฎหมาย: พระราชกำหนดการประกอบธุรกิจสินทรัพย์ดิจิทัล พ.ศ. 2561\nเนื้อหา: พระราชกำหนดการประกอบธุรกิจสินทรัพย์ดิจิทัล พ.ศ. 2561 มาตรา 68 ผู้ประกอบธุรกิจสินทรัพย์ดิจิทัลใดไม่ปฏิบัติตามประกาศหรือคำสั่งตามมาตรา 37 ต้องระวางโทษปรับไม่เกินห้าแสนบาท และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังมิได้ปฏิบัติให้ถูกต้อง'),
 Document(metadata={'law_name': 'พระราชบัญญัติวิชาชีพบัญชี พ.ศ. 2547'}, page_content='กฎหมาย: พระราชบัญญัติวิชาชีพบัญชี พ.ศ. 2547\nเนื้อหา: พระราชบัญญัติวิชาชีพบัญชี พ.ศ. 2547 มาตรา 65 ผู้ใดฝ่าฝืนมาตรา 10 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินหกหมื่นบาท หรือทั้งจำทั้งปรับ'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 358\nถ้าคำบอกกล่าวสนองมาถึงล่วงเวลา แต่เป็นที่เห็นประจักษ์ว่าคำบอกกล่าวนั้นได้ส่งโดยทางการ ซึ่งตามปรกติควรจะมาถึงภายในกำหนดไซร้ ผู้เสนอต้องบอกกล่าวแก่คู่กรณีอีกฝ่ายหนึ่งโดยพลันว่าคำสนองนั้นมาถึงเนิ่นช้า เว้นแต่จะได้บอกกล่าวเช่นนั้นก่อนแล้ว\nถ้าผู้เสนอละเลยไม่บอกกล่าวดังว่ามาในวรรคต้น ท่านให้ถือว่าคำบอกกล่าวสนองนั้นมิได้ล่วงเวลา'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 902\nถ้าตั๋วเงินลงลายมือชื่อของบุคคลหลายคน มีทั้งบุคคลซึ่งไม่อาจจะเป็นคู่สัญญาแห่งตั๋วเงินนั้นได้เลย หรือเป็นได้แต่ไม่เต็มผลไซร้ ท่านว่าการนี้ย่อมไม่กระทบกระทั่งถึงความรับผิดของบุคคลอื่น ๆ นอกนั้นซึ่งคงต้องรับผิดตามตั๋วเงิน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 455\nเมื่อกล่าวต่อไปเบื้องหน้าถึงเวลาซื้อขาย ท่านหมายความว่าเวลาซึ่งทำสัญญาซื้อขายสำเร็จบริบูรณ์'),
 Document(metadata={'law_name': 'พระราชบัญญัติทรัสต์เพื่อธุรกรรมในตลาดทุน พ.ศ. 2550'}, page_content='กฎหมาย: พระราชบัญญัติทรัสต์เพื่อธุรกรรมในตลาดทุน พ.ศ. 2550\nเนื้อหา: พระราชบัญญัติทรัสต์เพื่อธุรกรรมในตลาดทุน พ.ศ. 2550 มาตรา 17 สัญญาก่อตั้งทรัสต์จะมีข้อกำหนดที่ขัดหรือแย้งกับพระราชบัญญัตินี้มิได้ ข้อกำหนดของสัญญาก่อตั้งทรัสต์ที่ขัดหรือแย้งกับบทบัญญัติแห่งพระราชบัญญัตินี้ ให้เป็นโมฆะ'),
 Document(metadata={'law_name': 'พระราชบัญญัติกองทุนสำรองเลี้ยงชีพ พ.ศ. 2530'}, page_content='กฎหมาย: พระราชบัญญัติกองทุนสำรองเลี้ยงชีพ พ.ศ. 2530\nเนื้อหา: พระราชบัญญัติกองทุนสำรองเลี้ยงชีพ พ.ศ. 2530 มาตรา 24 สิทธิเรียกร้องเงินจากกองทุนตามมาตรา 23 มาตรา 23/2 และมาตรา 23/3 ไม่อาจโอนกันได้และไม่อยู่ในความรับผิดแห่งการบังคับคดี'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 618\nถ้าของนั้นได้ส่งไปโดยมีผู้ขนส่งหลายคนหลายทอด ท่านว่าผู้ขนส่งทั้งนั้นจะต้องรับผิดร่วมกันในการสูญหาย บุบสลาย หรือส่งชักช้า'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1090\nผู้เป็นหุ้นส่วนจำพวกจำกัดความรับผิดจะประกอบการค้าขายอย่างใด ๆ เพื่อประโยชน์ตนหรือเพื่อประโยชน์บุคคลภายนอกก็ได้ แม้ว่าการงานเช่นนั้นจะมีสภาพเป็นอย่างเดียวกันกับการค้าขายของห้างหุ้นส่วนก็ไม่ห้าม'),
 Document(metadata={'law_name': 'พระราชบัญญัติกำหนดความผิดเกี่ยวกับห้างหุ้นส่วนจดทะเบียน ห้างหุ้นส่วนจำกัด บริษัทจำกัด สมาคม และมูลนิธิ พ.ศ. 2499'}, page_content='กฎหมาย: พระราชบัญญัติกำหนดความผิดเกี่ยวกับห้างหุ้นส่วนจดทะเบียน ห้างหุ้นส่วนจำกัด บริษัทจำกัด สมาคม และมูลนิธิ พ.ศ. 2499\nเนื้อหา: พระราชบัญญัติกำหนดความผิดเกี่ยวกับห้างหุ้นส่วนจดทะเบียน ห้างหุ้นส่วนจำกัด บริษัทจำกัด สมาคม และมูลนิธิ พ.ศ. 2499 มาตรา 57 ในกรณีที่คณะกรรมการของสมาคมไม่แจ้งการเลิกสมาคมต่อนายทะเบียนภายในระยะเวลาที่กำหนดตามมาตรา 105 แห่งประมวลกฎหมายแพ่งและพาณิชย์ กรรมการของสมาคมนั้นมีความผิดทางพินัยต้องชำระค่าปรับเป็นพินัยไม่เกินคนละหนึ่งหมื่นบาท* เว้นแต่กรรมการผู้ใดของสมาคมนั้นจะพิสูจน์ได้ว่า การที่มิได้แจ้งนั้น มิได้เกิดจากการกระทำของตน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1684\nเมื่อความข้อใดข้อหนึ่งในพินัยกรรมอาจตีความได้เป็นหลายนัย ให้ถือเอาตามนัยที่จะสำเร็จผลตามความประสงค์ของผู้ทำพินัยกรรมนั้นได้ดีที่สุด'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 389\nถ้าการชำระหนี้ทั้งหมดหรือแต่บางส่วนกลายเป็นพ้นวิสัยเพราะเหตุอย่างใดอย่างหนึ่งอันจะโทษลูกหนี้ได้ไซร้ เจ้าหนี้จะเลิกสัญญานั้นเสียก็ได้'),
 Document(metadata={'law_name': 'พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558'}, page_content='กฎหมาย: พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558\nเนื้อหา: พระราชบัญญัติหลักประกันทางธุรกิจ พ.ศ. 2558 มาตรา 63 หากมีเหตุบังคับหลักประกันตามสัญญาหลักประกันทางธุรกิจ ให้ผู้รับหลักประกันมีหนังสือแจ้งผู้บังคับหลักประกันทราบโดยทางไปรษณีย์ลงทะเบียนตอบรับหรือโดยวิธีการอื่นที่แสดงว่าผู้บังคับหลักประกันได้รับหนังสือแล้ว\nให้ผู้บังคับหลักประกันกำหนดวัน เวลา และสถานที่ไต่สวนข้อเท็จจริงโดยเร็ว ซึ่งต้องไม่เกินเจ็ดวันนับแต่วันที่ได้รับหนังสือตามวรรคหนึ่ง และมีหนังสือแจ้งผู้ให้หลักประกันและผู้รับหลักประกันทราบโดยไม่ชักช้าโดยทางไปรษณีย์ลงทะเบียนตอบรับหรือโดยวิธีการอื่นที่แสดงว่าผู้รับได้รับหนังสือแล้ว ในการนี้ ให้แจ้งเหตุที่ผู้รับหลักประกันยกขึ้นบังคับหลักประกันและประเด็นการพิจารณา รวมทั้งสำเนาหนังสือของผู้รับหลักประกันตามวรรคหนึ่งไปด้วย\nในกรณีที่ผู้บังคับหลักประกันตายหรือไม่สามารถปฏิบัติหน้าที่ได้เนื่องจากขาดคุณสมบัติหรือมีลักษณะต้องห้ามตามมาตรา 55 ก่อนดำเนินการตามวรรคหนึ่ง ให้คู่สัญญาตกลงกันเลือกผู้รับใบอนุญาตอื่นเป็นผู้บังคับหลักประกัน และให้นำบทบัญญัติมาตรา 12 วรรคสอง มาใช้บังคับแก่การเลือกผู้บังคับหลักประกันตามมาตรานี้โดยอนุโลม\nในกรณีที่คู่สัญญาไม่สามารถตกลงกันเลือกผู้รับใบอนุญาตอื่นเป็นผู้บังคับหลักประกันแทนภายในสิบห้าวันนับแต่วันที่มีเหตุตามวรรคสาม คู่สัญญาฝ่ายใดฝ่ายหนึ่งอาจยื่นคำร้องต่อศาลเพื่อมีคำสั่งแต่งตั้งผู้รับใบอนุญาตคนหนึ่งหรือหลายคนตามที่ศาลเห็นสมควรเป็นผู้บังคับหลักประกันแทน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1598/9\nการร้องขอให้ถอนผู้ปกครองตามมาตรา 1598/8 นั้น ผู้อยู่ในปกครองซึ่งมีอายุไม่ต่ำกว่าสิบห้าปีบริบูรณ์ หรือญาติของผู้อยู่ในปกครองหรืออัยการจะเป็นผู้ร้องขอก็ได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1389\nถ้าความต้องการแห่งเจ้าของสามยทรัพย์เปลี่ยนแปลงไป ท่านว่าความเปลี่ยนแปลงนั้นไม่ให้สิทธิแก่เจ้าของสามยทรัพย์ที่จะทำให้เกิดภาระเพิ่มขึ้นแก่ภารยทรัพย์ได้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 45\nภูมิลำเนาของคนไร้ความสามารถ ได้แก่ภูมิลำเนาของผู้อนุบาล'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 820\nตัวการย่อมมีความผูกพันต่อบุคคลภายนอกในกิจการทั้งหลายอันตัวแทนหรือตัวแทนช่วงได้ทำไปภายในขอบอำนาจแห่งฐานตัวแทน'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 1247\nการชำระบัญชีห้างหุ้นส่วนจดทะเบียน หรือห้างหุ้นส่วนจำกัดหรือบริษัทจำกัดซึ่งล้มละลายนั้น ให้จัดทำไปตามบทกฎหมายลักษณะล้มละลายที่คงใช้อยู่ตามแต่จะทำได้\nรัฐมนตรีเจ้าหน้าที่จะออกกฎกระทรวงว่าด้วยการชำระบัญชีห้างหุ้นส่วนและบริษัท และกำหนดอัตราค่าฤชาธรรมเนียมก็ออกได้'),
 Document(metadata={'law_name': 'พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535'}, page_content='กฎหมาย: พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535\nเนื้อหา: พระราชบัญญัติหลักทรัพย์และตลาดหลักทรัพย์ พ.ศ. 2535 มาตรา 312 กรรมการ ผู้จัดการ หรือบุคคลใดซึ่งรับผิดชอบในการดำเนินงานของนิติบุคคลใดตามพระราชบัญญัตินี้ กระทำหรือยินยอมให้กระทำการ ดังต่อไปนี้\n(1) ทำให้เสียหาย ทำลาย เปลี่ยนแปลง ตัดทอน หรือปลอมบัญชีเอกสาร หรือหลักประกันของนิติบุคคลดังกล่าว หรือที่เกี่ยวกับนิติบุคคลดังกล่าว\n(2) ลงข้อความเท็จหรือไม่ลงข้อความสำคัญในบัญชีหรือเอกสารของนิติบุคคลหรือที่เกี่ยวกับนิติบุคคลนั้น หรือ\n(3) ทำบัญชีไม่ครบถ้วน ไม่ถูกต้อง ไม่เป็นปัจจุบันหรือไม่ตรงต่อความเป็นจริง\nถ้ากระทำหรือยินยอมให้กระทำเพื่อลวงให้นิติบุคคลดังกล่าวหรือผู้ถือหุ้นขาดประโยชน์อันควรได้ หรือลวงบุคคลใด ๆ ต้องระวางโทษจำคุกตั้งแต่ห้าปีถึงสิบปี และปรับตั้งแต่ห้าแสนบาทถึงหนึ่งล้านบาท'),
 Document(metadata={'law_name': 'พระราชบัญญัติการบัญชี พ.ศ. 2543'}, page_content='กฎหมาย: พระราชบัญญัติการบัญชี พ.ศ. 2543\nเนื้อหา: พระราชบัญญัติการบัญชี พ.ศ. 2543 มาตรา 36 ผู้ใดขัดขวางการปฏิบัติหน้าที่ของสารวัตรใหญ่บัญชีหรือสารวัตรบัญชี ซึ่งปฏิบัติการตามมาตรา 22 ต้องระวางโทษจำคุกไม่เกินหนึ่งปี หรือปรับไม่เกินสองหมื่นบาท หรือทั้งจำทั้งปรับ\nผู้ใดไม่อำนวยความสะดวกแก่สารวัตรใหญ่บัญชีหรือสารวัตรบัญชีซึ่งปฏิบัติหน้าที่ตามมาตรา 22 หรือฝ่าฝืนคำสั่งของสารวัตรใหญ่บัญชีหรือสารวัตรบัญชีซึ่งสั่งการตามมาตรา 24 ต้องระวางโทษจำคุกไม่เกินหนึ่งเดือน หรือปรับไม่เกินสองพันบาท หรือทั้งจำทั้งปรับ'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 783\nผู้ทรงเอกสารอันมีทั้งใบรับของคลังสินค้าและประทวนสินค้านั้น จะให้นายคลังสินค้าแยกสินค้าที่เก็บรักษาไว้ออกเป็นหลายส่วนและให้ส่งมอบเอกสารแก่ตนส่วนละใบก็ได้ ในกรณีเช่นนี้ผู้ทรงเอกสารต้องคืนเอกสารเดิมแก่นายคลังสินค้า\nอนึ่ง ค่าใช้จ่ายในการแยกสินค้าและการส่งมอบเอกสารใหม่นั้น ผู้ทรงเอกสารต้องรับใช้'),
 Document(metadata={'law_name': 'ประมวลกฎหมายแพ่งและพาณิชย์'}, page_content='กฎหมาย: ประมวลกฎหมายแพ่งและพาณิชย์\nเนื้อหา: ประมวลกฎหมายแพ่งและพาณิชย์ มาตรา 804\nถ้าในสัญญาอันเดียวตัวการคนเดียวตั้งตัวแทนหลายคนเพื่อแก่การอันเดียวกันไซร้ ท่านให้สันนิษฐานไว้ก่อนว่าตัวแทนจะต่างคนต่างทำการนั้น ๆ แยกกันไม่ได้'),

## 3. Select LLM

In [5]:
from neo4j_graphrag.llm import OllamaLLM
# llm = OllamaLLM(
#     model_name="llama3",
#     # model_params={"options": {"temperature": 0}, "format": "json"},
#     host="http://localhost:11434",  # when using a remote server
# )

os.environ["OPENAI_API_KEY"] = os.getenv("openrouter_API_key") # ใส่ OpenRouter Key ของคุณตรงนี้

# 2. เรียกใช้งาน โดยใส่ base_url กำกับไว้ข้างนอก
llm = OpenAILLM(
    model_name="openai/gpt-4o-mini", 
    base_url="https://openrouter.ai/api/v1",
    model_params={
        "temperature": 0
    }
)
# llm.invoke("say hello-world")

## 4. Graph Construction

In [ ]:
# llm = ChatOpenAI(api_key=os.getenv("openrouter_API_key") ,temperature=0, model="openai/gpt-4o-mini", base_url="https://openrouter.ai/api/v1")
# llm = OllamaLLM(model="llama3", )

entities = [
    {"label": "law_name", "properties": [{"name": "law_name", "type": "STRING", "name": "section_num", "type": "STRING"}]},  
]

relations = [
    {"label": "CONTAINS", "source": "law_name", "target": "section_num"},
]

kg_builder = SimpleKGPipeline(
    driver=driver,
    llm=llm,
    embedder=neo4j_embedder,
    entities=entities,
    relations=relations,
    neo4j_database=DATABASE_NAME,
    from_pdf=False,
    )

In [50]:
import time
from langchain_community.callbacks import get_openai_callback

start_time = time.perf_counter()
with get_openai_callback() as cb:
    for i in range(len(documents)):
        #นำเข้า Neo4j ทีละ Document (ซึ่งแต่ละ Document ก็คือ Section ที่ถูก Chunk แล้ว) สิ่งที่นำเข้าเป็น json format
        await kg_builder.run_async(text=documents[i].page_content, document_metadata=documents[i].metadata,) 
end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.4f} seconds")
print(f"Total Tokens: {cb.total_tokens}")
print(f"Prompt Tokens: {cb.prompt_tokens}")
print(f"Completion Tokens: {cb.completion_tokens}")

LLM response has improper format for chunk_index=0

Elapsed time: 497.3945 seconds
Total Tokens: 0
Prompt Tokens: 0
Completion Tokens: 0

## 5. Retrieval

### 5.1 Vector Retriever เหมือน RAG ธรรมดา

In [6]:
# Initialize the retriever
retriever = VectorRetriever(
     driver,
     index_name= "text_embeddings",
     embedder=neo4j_embedder,
     return_properties=["text"]
)
query = "ถ้ามีคนประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตต้องระวางโทษอย่างไร"
result = retriever.search(query_text=query, top_k=5)
result

You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

RetrieverResult(items=[RetrieverResultItem(content="{'text': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 132 ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน'}", metadata={'score': 0.9034852981567383, 'nodeLabels': ['Section'], 'id': '4:479141a0-c13e-4e91-8882-94f287492b94:0'}), RetrieverResultItem(content="{'text': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 125 ผู้ใดประกอบกิจการในลักษณะเป็นการประกอบธุรกิจสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 16 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน'}", metadata={'score': 0.8719487190246582, 'nodeLabels': ['Section'], 'id': '4:479141a0-c13e-4e91-8882-94f287492b94:2339'}), RetrieverResultItem(content="{'text': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 134 ผู้ใดประกอบกิจการในลักษณะเป็นสำนักหักบัญชีสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 75 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน'}", metadata={'score': 0.860811710357666, 'nodeLabels': ['Section'], 'id': '4:479141a0-c13e-4e91-8882-94f287492b94:3035'}), RetrieverResultItem(content="{'text': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 127 ศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าใดไม่ปฏิบัติตามเงื่อนไขที่กำหนดตามมาตรา 20 วรรคสอง ซึ่งมาตรา 74 ให้นำมาใช้บังคับโดยอนุโลม ต้องระวางโทษปรับไม่เกินหนึ่งแสนบาท และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน'}", metadata={'score': 0.8334555625915527, 'nodeLabels': ['Section'], 'id': '4:479141a0-c13e-4e91-8882-94f287492b94:1997'}), RetrieverResultItem(content="{'text': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 133 ศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าใดฝ่าฝืนหรือไม่ปฏิบัติตามมาตรา 67 ต้องระวางโทษปรับไม่เกินสามแสนบาท และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน'}", metadata={'score': 0.8312220573425293, 'nodeLabels': ['Section'], 'id': '4:479141a0-c13e-4e91-8882-94f287492b94:2000'})], metadata={'query_vector': [-0.044647216796875, -0.0129547119140625, -0.026275634765625, 0.028900146484375, -0.00047969818115234375, 0.006046295166015625, -0.002002716064453125, 0.01329803466796875, -0.02276611328125, -0.00797271728515625, -0.0190277099609375, -0.02239990234375, -0.0288543701171875, -0.0006723403930664062, -0.0064239501953125, -0.04351806640625, 0.0712890625, -0.0286102294921875, 0.017578125, 0.005939483642578125, -0.036376953125, 0.0093841552734375, -0.0259552001953125, 0.00446319580078125, 0.054779052734375, 0.027587890625, -0.060638427734375, -0.01042938232421875, 0.0030059814453125, -0.0467529296875, -0.046875, -0.01544952392578125, -0.0264129638671875, -0.00994110107421875, 0.0377197265625, -0.010101318359375, -0.0010519027709960938, 0.003681182861328125, -0.02447509765625, -0.033905029296875, 0.01861572265625, -0.0240631103515625, 0.0004417896270751953, -0.0181427001953125, 0.018585205078125, -0.057861328125, -0.01171875, -0.0286102294921875, -0.030487060546875, 0.006252288818359375, -0.0218963623046875, -0.0131988525390625, 0.0212249755859375, -0.01244354248046875, 0.0633544921875, 0.037811279296875, 0.0308380126953125, -0.03692626953125, 0.01025390625, -0.023956298828125, -0.04034423828125, -0.0242156982421875, 0.02935791015625, 0.020477294921875, -0.0078582763671875, 0.049530029296875, 0.023529052734375, -0.040557861328125, 0.02667236328125, -0.044097900390625, 0.00812530517578125, 0.0472412109375, 0.0108795166015625, -0.02960205078125, -0.0731201171875, -0.009857177734375, -0.007717132568359375, 0.01947021484375, 0.025146484375, -0.0679931640625, 0.01371002197265625, -0.007167816162109375, -0.01013946533203125, 0.058837890625, 0.042938232421875, -0.0004737377166748047, 0.01026153564453125, 0.01947021484375, -0.01354217529296875, -0.038848876953125, -0.00836944580078125, 0.0091400146484375, 0.0197906494140625, 0.00771331787109375, -0.028594970703125, -0.0438232421875, -0.020721435546875, -0.0134124755859375, 0.0008769035339355469, 0.0215911865234375, -0.044036865234375, 0.00868988037109375, 0.042633056640625, -0.03466796875, 0.025360107421875, 0.012939453125, 0.0035190582275390625, 0.031951904296875, -0.030120849609375, -0.02984619140625, -0.01136016845703125, -0.022705078125, 0.022674560546875, -0.0021820068359375, 0.0216217041015625, 0.007598876953125, 0.01351165771484375, -0.022430419921875, 0.0023059844970703125, -0.004398345947265625, -0.0286102294921875, 0.02691650390625, 0.0257415771484375, -0.04937744140625, -0.00887298583984375, -0.025054931640625, 0.016937255859375, -0.03704833984375, -0.00980377197265625, 0.038787841796875, 0.032623291015625, 0.0018520355224609375, -0.055419921875, -0.033782958984375, -0.037322998046875, -0.010467529296875, -0.002506256103515625, -0.054779052734375, -0.01324462890625, -0.0191802978515625, 0.006805419921875, 0.00830078125, 0.0117950439453125, -0.00353240966796875, 0.0208892822265625, -0.039581298828125, 0.043182373046875, -0.017181396484375, 0.035003662109375, -0.0138092041015625, -0.034393310546875, -0.00281524658203125, 0.0455322265625, -0.01153564453125, 0.0156402587890625, -0.0148468017578125, -0.059295654296875, -0.0195770263671875, 0.0033702850341796875, -0.007320404052734375, -0.01898193359375, 0.05816650390625, -0.03277587890625, 0.0289459228515625, 0.029632568359375, 0.0509033203125, -0.05511474609375, -0.01406097412109375, -0.0015354156494140625, 0.036376953125, 0.035614013671875, 0.01218414306640625, 0.06597900390625, -0.057464599609375, 0.0039825439453125, 0.0323486328125, 0.0101165771484375, 0.022247314453125, -0.047943115234375, -0.01541900634765625, -0.0267791748046875, 0.04052734375, -0.028656005859375, 0.0083770751953125, 0.036041259765625, 0.0355224609375, 0.0458984375, 0.0214385986328125, 0.03076171875, 0.010223388671875, -0.01102447509765625, -0.0305938720703125, -0.0322265625, 0.035552978515625, 0.00399017333984375, 0.0281829833984375, -0.01094818115234375, -0.0154876708984375, 0.041412353515625, 0.00962066650390625, -0.03887939453125, -0.00112152099609375, 0.0216217041015625, -0.0263671875, -0.0367431640625, 0.0026035308837890625, -0.020050048828125, -0.0227813720703125, -0.01885986328125, -0.0496826171875, 0.0010614395141601562, -0.01824951171875, -0.0287017822265625, -0.03515625, -0.00568389892578125, 0.00525665283203125, 0.01480865478515625, 0.003459930419921875, 0.0011997222900390625, 0.00484466552734375, -0.02996826171875, 0.0390625, -0.0006966590881347656, 0.0276336669921875, 0.0249786376953125, 0.045135498046875, 0.0126953125, 0.031829833984375, -0.0355224609375, -0.0556640625, -0.01248931884765625, -0.0079193115234375, -0.0242767333984375, -0.0097503662109375, 0.09552001953125, 0.048309326171875, -0.0243072509765625, 0.0169677734375, 0.045684814453125, 0.0197906494140625, -0.06060791015625, 0.01215362548828125, 0.041839599609375, 0.01117706298828125, -0.00592041015625, 0.05938720703125, -0.059661865234375, -0.0198211669921875, -0.0203857421875, -0.00473785400390625, 0.046478271484375, -0.01160430908203125, -0.03753662109375, 0.0596923828125, 0.0181884765625, 0.01270294189453125, -0.03271484375, -0.01285552978515625, -0.001819610595703125, -0.002948760986328125, 0.014434814453125, -0.0288238525390625, 0.0234222412109375, 0.034942626953125, -0.0300140380859375, -5.27501106262207e-05, -0.046142578125, 0.0139007568359375, 0.039306640625, -0.0233306884765625, -0.01873779296875, -0.0041656494140625, 0.0208587646484375, 0.01107025146484375, 0.031280517578125, -0.050994873046875, 0.033294677734375, 0.006923675537109375, 0.005947113037109375, 0.03765869140625, -0.0318603515625, 0.0030841827392578125, 0.019287109375, -0.01849365234375, 0.03460693359375, 0.01140594482421875, 0.01262664794921875, 0.0157012939453125, 0.00807952880859375, -0.041534423828125, -0.005062103271484375, -0.011566162109375, 0.0960693359375, 0.00018894672393798828, -0.055419921875, 0.0239715576171875, -0.0280609130859375, -0.12939453125, 0.0233001708984375, -0.0287017822265625, -0.046234130859375, -0.01505279541015625, -0.020233154296875, -0.026214599609375, -0.019195556640625, 0.0195159912109375, 0.023223876953125, 0.009979248046875, -0.052947998046875, -0.0082244873046875, -0.040863037109375, 0.002422332763671875, -0.02630615234375, 0.0109405517578125, -0.005451202392578125, 0.004154205322265625, -0.012237548828125, 0.02276611328125, -0.0080718994140625, 0.0030612945556640625, -0.040252685546875, -0.0341796875, 0.0069427490234375, 0.00672149658203125, 0.01271820068359375, -0.0097808837890625, -0.0228118896484375, 0.050323486328125, 0.02398681640625, -0.024627685546875, 0.01319122314453125, 0.022705078125, -0.0279388427734375, 0.0177764892578125, -0.045684814453125, 0.0308837890625, 0.0015478134155273438, 0.004974365234375, 0.03497314453125, -0.00865936279296875, 0.00634002685546875, 0.009185791015625, 0.0117950439453125, 0.0048065185546875, -0.015106201171875, 0.024078369140625, 0.0567626953125, -0.052337646484375, 0.035308837890625, -0.0293426513671875, -0.0254974365234375, -0.00011545419692993164, -0.002544403076171875, 0.04931640625, 0.0206451416015625, -0.043121337890625, 0.013275146484375, -0.025390625, -0.034759521484375, -0.005096435546875, -0.02545166015625, -0.01122283935546875, -0.0146636962890625, 0.01375579833984375, 0.02020263671875, -0.01280975341796875, 0.01556396484375, 0.0018939971923828125, 0.04095458984375, -0.0177764892578125, -0.01070404052734375, 0.004970550537109375, 0.015960693359375, 0.0048065185546875, 0.00626373291015625, -0.010711669921875, -0.1151123046875, -0.0191497802734375, 0.042938232421875, -0.0287933349609375, -0.006778717041015625, -0.035430908203125, -0.015472412109375, 0.026153564453125, 0.0266265869140625, -0.00970458984375, 0.243408203125, -0.003902435302734375, 0.00518798828125, 0.0243072509765625, 0.03179931640625, -0.04736328125, 0.04107666015625, -0.0162353515625, -0.0004048347473144531, -0.0224761962890625, -0.01248931884765625, 0.006500244140625, 0.0068359375, 0.0163116455078125, -0.01441192626953125, -0.00707244873046875, 0.0008392333984375, -0.023529052734375, 0.06341552734375, -0.036468505859375, 0.01081085205078125, -0.01122283935546875, 0.0246734619140625, 0.0239715576171875, -0.034942626953125, -0.059967041015625, 0.01222991943359375, 0.029449462890625, -0.003734588623046875, 0.0101470947265625, 0.006290435791015625, -0.0181121826171875, -0.00298309326171875, -0.0019197463989257812, -0.019744873046875, 0.0233001708984375, 0.0235748291015625, -0.02337646484375, -0.01546478271484375, 0.057586669921875, -0.0205230712890625, -0.019805908203125, -0.004268646240234375, 0.001369476318359375, -0.0262451171875, -0.018585205078125, -0.0004940032958984375, 0.0283966064453125, -0.0256195068359375, 0.0029888153076171875, -0.03912353515625, -0.0205841064453125, -0.022918701171875, 0.0088653564453125, -0.0214996337890625, -0.0281219482421875, -0.0219879150390625, 0.00434112548828125, -0.024169921875, 0.0175018310546875, 0.0192108154296875, -0.00792694091796875, -0.005664825439453125, 0.0045928955078125, -0.0217132568359375, 0.047821044921875, 0.003894805908203125, 0.0095367431640625, 0.05511474609375, 0.01617431640625, -0.01511383056640625, -0.0357666015625, -0.0230560302734375, -0.004795074462890625, 0.0382080078125, 0.0404052734375, -0.0095062255859375, 0.039764404296875, 0.038787841796875, 0.0438232421875, -0.01512908935546875, -0.04510498046875, 0.005767822265625, 0.002696990966796875, -0.01324462890625, -0.031494140625, -0.0016422271728515625, 0.0675048828125, -0.03839111328125, -0.046783447265625, 0.025421142578125, -0.032012939453125, -0.0335693359375, 0.0728759765625, -0.01465606689453125, 0.0292816162109375, -0.0013179779052734375, 0.00888824462890625, -0.038177490234375, 0.01390838623046875, 0.0247344970703125, -0.0023021697998046875, 0.0458984375, 0.022918701171875, 0.0106201171875, -0.00820159912109375, -0.0050201416015625, 0.02716064453125, 0.015472412109375, -0.0294036865234375, -0.01355743408203125, 0.0096588134765625, -0.0271453857421875, -0.0094146728515625, 0.01076507568359375, 0.0302581787109375, -0.0268402099609375, -0.01435089111328125, 0.0391845703125, 0.042755126953125, -0.005306243896484375, 0.04986572265625, -0.041351318359375, 0.044921875, -0.0245208740234375, 0.038360595703125, -0.0286712646484375, 0.061859130859375, 0.039703369140625, 0.0380859375, -0.0178985595703125, -0.0151824951171875, -0.0260772705078125, 0.03790283203125, 0.05157470703125, -0.0218048095703125, 0.01187896728515625, -0.006549835205078125, 0.04168701171875, 0.02447509765625, -0.0220794677734375, 0.037811279296875, -0.0014209747314453125, 0.03936767578125, 0.0098876953125, -0.04412841796875, -0.0333251953125, -0.023162841796875, -0.03021240234375, -0.002216339111328125, 0.02825927734375, -0.0159912109375, 0.00888824462890625, -0.035400390625, 0.0261077880859375, -0.03753662109375, -0.0242462158203125, -0.025054931640625, 0.049285888671875, -0.028167724609375, 0.0224456787109375, -0.041717529296875, -0.0181732177734375, 0.065673828125, -0.00616455078125, 0.076171875, 0.004638671875, 0.045318603515625, -0.00010120868682861328, 0.0013628005981445312, 0.0159912109375, -0.031341552734375, -0.036529541015625, 0.025543212890625, 0.027740478515625, 0.002368927001953125, -0.066162109375, -0.003452301025390625, -0.039825439453125, -0.0094146728515625, 0.005802154541015625, 0.0269622802734375, 0.04644775390625, -0.07525634765625, -0.002895355224609375, -0.007564544677734375, 0.0213165283203125, -0.0237579345703125, 0.009368896484375, -0.01326751708984375, -0.017120361328125, 0.07489013671875, 0.02349853515625, -0.012481689453125, 0.028228759765625, 0.058807373046875, 0.014556884765625, -0.023681640625, -0.0037517547607421875, 0.019775390625, -0.010894775390625, -0.00989532470703125, -0.005207061767578125, -0.0081939697265625, 0.024871826171875, -0.030303955078125, -0.030517578125, 0.03076171875, 0.003177642822265625, -0.04449462890625, 0.009307861328125, -0.010162353515625, -0.00969696044921875, -0.00623321533203125, -0.0028514862060546875, -0.0239105224609375, 0.036102294921875, 0.08355712890625, 0.048919677734375, -0.0206146240234375, 0.006328582763671875, 0.02099609375, 0.021942138671875, -0.051727294921875, -0.0017080307006835938, -0.0523681640625, 0.0193328857421875, 0.02362060546875, 0.022674560546875, 0.02471923828125, 0.01544952392578125, -0.0023193359375, 0.0008955001831054688, 0.0181884765625, -0.00759124755859375, -0.01221466064453125, 0.0098876953125, 0.01436614990234375, 0.022491455078125, 0.007785797119140625, 0.037109375, -0.034912109375, 0.0711669921875, 0.0307464599609375, 0.00902557373046875, 0.0214080810546875, -0.040557861328125, 0.030670166015625, 0.040496826171875, 0.042236328125, -0.03143310546875, -0.0220947265625, -0.00908660888671875, -0.0382080078125, -0.0120697021484375, 0.0284576416015625, 0.00026416778564453125, -0.006786346435546875, -0.023895263671875, -0.03375244140625, -0.015655517578125, 0.007503509521484375, -0.0225677490234375, 0.00984954833984375, -0.0038433074951171875, -0.08026123046875, 0.021514892578125, -0.038177490234375, -0.037139892578125, -0.049560546875, -0.0181732177734375, 0.01490020751953125, -0.00911712646484375, -0.0235137939453125, -0.00044465065002441406, 0.0195159912109375, -0.0750732421875, 0.0587158203125, 0.017303466796875, 7.712841033935547e-05, 0.0256195068359375, -0.0243072509765625, 0.0310516357421875, -0.021881103515625, 0.00873565673828125, 0.0439453125, 0.005069732666015625, 0.0029125213623046875, -0.031280517578125, -0.00934600830078125, 0.0005741119384765625, -0.003032684326171875, -0.0308380126953125, 0.020538330078125, -0.04205322265625, 0.0650634765625, -0.005825042724609375, -0.006229400634765625, -0.03558349609375, 0.035858154296875, -0.021759033203125, 0.01210784912109375, -0.048858642578125, -0.005695343017578125, 0.002735137939453125, 0.01535797119140625, 0.0279083251953125, -0.036865234375, -0.01061248779296875, 0.07098388671875, 0.060333251953125, -0.01157379150390625, -0.004978179931640625, -0.01262664794921875, -0.0089874267578125, -0.015380859375, 0.0192413330078125, 0.00893402099609375, 0.002101898193359375, 0.0202789306640625, -0.0275115966796875, 0.00439453125, 0.0186614990234375, -0.0212860107421875, -0.038970947265625, 0.00786590576171875, -0.0196533203125, -0.01702880859375, -0.0222320556640625, -0.00284576416015625, 0.0034046173095703125, -0.004581451416015625, 0.0137481689453125, -0.027740478515625, 0.0065460205078125, 0.024139404296875, 0.0021152496337890625, 0.001220703125, 0.06585693359375, -0.00885009765625, 0.037261962890625, -0.0406494140625, 0.077880859375, -0.037841796875, 0.032623291015625, -0.03619384765625, -0.003543853759765625, -0.03533935546875, -0.040924072265625, -0.0189971923828125, -0.00794219970703125, 0.0048065185546875, 0.0006546974182128906, -0.0283660888671875, 0.0291595458984375, -0.046630859375, 0.0067138671875, -0.0023860931396484375, 0.0220947265625, 0.004852294921875, -0.018829345703125, 0.06243896484375, -0.0201568603515625, 0.036102294921875, 0.01678466796875, -0.0099334716796875, -0.0267791748046875, 0.01538848876953125, 0.025421142578125, 0.01476287841796875, -6.496906280517578e-06, -0.03936767578125, -0.03265380859375, 0.0169525146484375, -0.01325225830078125, 0.04229736328125, -0.0287017822265625, -0.00925445556640625, -0.02484130859375, -0.0144195556640625, -0.047088623046875, -0.038360595703125, -0.020843505859375, 0.018890380859375, 0.0093994140625, 0.037628173828125, -0.0007143020629882812, -0.0209503173828125, 0.004703521728515625, -0.000690460205078125, -0.038421630859375, -0.0299072265625, -0.0192413330078125, 0.0273590087890625, -0.164306640625, -0.002109527587890625, -0.0175628662109375, -0.01153564453125, 0.0009055137634277344, -0.0184326171875, -0.004016876220703125, -0.06298828125, -0.0115814208984375, 0.05120849609375, -0.0031223297119140625, 0.09521484375, 0.006526947021484375, -0.0177764892578125, 0.00970458984375, 0.030548095703125, 0.01364898681640625, 0.0189971923828125, -0.00937652587890625, -0.04742431640625, -0.04620361328125, 0.02099609375, -0.0129547119140625, -0.031494140625, -0.046661376953125, 0.0206146240234375, -0.046783447265625, -0.0212249755859375, -0.0421142578125, -0.01309967041015625, -0.022369384765625, -0.0070953369140625, 0.004505157470703125, 0.0494384765625, 0.023834228515625, -0.0283203125, 0.01343536376953125, -0.0185089111328125, 0.00018835067749023438, -0.01532745361328125, -0.0165252685546875, 0.026031494140625, -0.0234527587890625, -0.01318359375, 0.0299072265625, -0.0086669921875, 0.0183563232421875, 0.005443572998046875, -0.0208282470703125, -0.040740966796875, -0.004703521728515625, -0.02252197265625, -0.093994140625, 0.00493621826171875, 0.0305938720703125, 0.0447998046875, -0.053680419921875, -0.0077362060546875, 0.0052337646484375, 0.030975341796875, -0.019287109375, -0.0021114349365234375, -0.040130615234375, 0.013946533203125, -0.044281005859375, 0.019195556640625, -0.0250701904296875, 0.038543701171875, 0.019500732421875, -0.0189361572265625, -0.00910186767578125, 0.0007886886596679688, 0.021881103515625, -0.0181427001953125, 0.0254364013671875, 0.053375244140625, 0.0022125244140625, 0.0199432373046875, 0.0004165172576904297, -0.01328277587890625, -0.0210113525390625, -0.01434326171875, 0.00708770751953125, -0.038299560546875, 0.0340576171875, 0.043212890625, -0.029266357421875, 0.0165557861328125, 0.0033721923828125, -0.0218963623046875, -0.063720703125, -0.019622802734375, -0.0103607177734375, 0.03912353515625, -0.01238250732421875, 0.033905029296875, -0.01438140869140625, -0.039337158203125, -0.003383636474609375, 0.00836181640625, -0.038970947265625, -0.007045745849609375, 0.01214599609375, -0.006664276123046875, -0.04449462890625, 0.0287322998046875, -0.01617431640625, 0.0040435791015625, 0.0153045654296875, -0.00897979736328125, 0.0018625259399414062, 0.0121917724609375, 0.0401611328125,

In [ ]:
# ดึงเนื้อหาของอันแรก
first_result = result.items[0].content
# ดึงค่า Score (ความเหมือน)
first_score = result.items[0].metadata['score']

print(f"Score: {first_score}")
print(f"Content: {first_result}")

Score: 0.9035258293151855
Content: {'text': 'กฎหมาย: พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546\nมาตรา: 132\nเนื้อหา: พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 132 ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน'}

### 5.2 Vector Cypher Retriever 
- ใช้ Cosine similarity เทียบความคล้าย
- Cypher query เข้าไป (ต้องมีการกำหนดเอง ดีที่สุดคืออิงจาก Schema)

In [5]:
schema = get_schema(driver)
schema

'Node properties:\nSection {section_num: STRING, id: INTEGER, text: STRING, embedding: LIST, law_id: STRING, law_name: STRING}\nRelationship properties:\n\nThe relationships:\n(:Section)-[:REFERENCES_TO]->(:Section)'

In [7]:
chunk_to_law_query = """
// 1. กระโดดจาก Node หลัก (Parent) ไปหา Node ที่ถูกอ้างอิง (Children)
OPTIONAL MATCH (node)-[:REFERENCES_TO]->(referencedSection)

// 2. รวบรวมข้อมูล Children ไว้เป็น List โดยดึง Text มาด้วย
WITH node, score, 
     collect({
         law_name: referencedSection.law_name, 
         section_num: referencedSection.section_num,
         text: referencedSection.text
     }) AS children_nodes

// 3. RETURN ผลลัพธ์: 
// ให้ node.text เป็น "Parent Content"
// และ Metadata เก็บข้อมูลรายละเอียดของ Parent พร้อมลิสต์ของ Children
RETURN 
    node.text AS content, 
    score, 
    {
        parent_law_name: node.law_name,
        parent_section_num: node.section_num,
        children: [c in children_nodes WHERE c.law_name IS NOT NULL]
    } AS metadata
"""

# ประกาศ retriever เหมือนเดิม
vector_cypher_retriever = VectorCypherRetriever(
    driver=driver,
    index_name="text_embeddings",
    embedder=neo4j_embedder,
    retrieval_query=chunk_to_law_query
)

In [35]:
query = "ถ้ามีคนประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตต้องระวางโทษอย่างไร" # ข้อ 1
result = vector_cypher_retriever.get_search_results(query_text=query, top_k=3)
print(len(result.records))
result.records[0].data()
# for item in result.items:
#     print(item.content)

3

{'content': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 132 ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน',
 'score': 0.9034852981567383,
 'metadata': {'parent_section_num': '132',
  'parent_law_name': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546',
  'children': [{'text': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546 มาตรา 54 ศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าต้องเป็นนิติบุคคลประเภทบริษัทมหาชนจำกัดและได้รับใบอนุญาตจากคณะกรรมการ ก.ล.ต.\nศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าที่เปิดให้เฉพาะผู้ลงทุนสถาบันซื้อขายสัญญาซื้อขายล่วงหน้าเพื่อตนเองต้องเป็นนิติบุคคลประเภทบริษัทจำกัดหรือบริษัทมหาชนจำกัดและจดทะเบียนกับสำนักงาน ก.ล.ต.\nการขออนุญาต การขอจดทะเบียน การออกใบอนุญาต และการรับจดทะเบียนให้เป็นไปตามหลักเกณฑ์ ที่คณะกรรมการ ก.ล.ต. ประกาศกำหนด',
    'section_num': '54',
    'law_name': 'พระราชบัญญัติสัญญาซื้อขายล่วงหน้า พ.ศ. 2546'}]}}

## 6. ใช้ Typhoon QA

In [10]:
os.environ["OPENAI_API_KEY"] = os.getenv("thai_llm_API_key")

model = "typhoon"
# 2. สร้าง LLM Object ให้ถูกต้องสำหรับ neo4j-graphrag
llm = OpenAILLM(
    model_name="typhoon-v2.5-30b-a3b-instruct",
    # สำคัญ: base_url ต้องหยุดอยู่ที่ /v1 (ห้ามมี /chat/completions ต่อท้าย)
    base_url=f"https://api.opentyphoon.ai/v1",
    # ต้องระบุ api_key เป็น string เสมอ (แม้จะเป็นค่าว่างก็ต้องใส่ "") เพื่อป้องกัน TypeError
    model_params={
        "temperature": 0.1,
        "max_tokens": 8192, 
    }
)
# llm.invoke("สวัสดี")

### คำตอบข้อ 1

In [11]:
query = "ถ้ามีคนประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตต้องระวางโทษอย่างไร" # ข้อ 1

result = GraphRAG(llm=llm,retriever=vector_cypher_retriever)
print(result.search(query_text=query, retriever_config= {"top_k": 10}).answer)

ผู้ใดประกอบกิจการในลักษณะเป็นศูนย์ซื้อขายสัญญาซื้อขายล่วงหน้าโดยไม่ได้รับใบอนุญาตหรือไม่ได้จดทะเบียนตามมาตรา 54 ต้องระวางโทษจำคุกไม่เกินสามปี หรือปรับไม่เกินสามแสนบาท หรือทั้งจำทั้งปรับ และปรับอีกไม่เกินวันละหนึ่งหมื่นบาทตลอดเวลาที่ยังฝ่าฝืน

### คำตอบข้อ Ref เยอะๆ

In [12]:
# query = "บทบัญญัติในหมวด 2 ว่าด้วยตั๋วแลกเงินที่สามารถนำมาใช้กับตั๋วสัญญาใช้เงินมีมาตราใดบ้าง"

# result = GraphRAG(llm=llm,retriever=vector_cypher_retriever)
# print(result.search(query_text=query, retriever_config= {"top_k": 10}).answer)